apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 8080
  selector:
    app: wordpress
    tier: mysql